<header>
    <div class="container">
        <div id="logo">
            <img src="<?= BASEURL ?>public/img/logo.jpg" class="img-responsive">
        </div>
    </div>
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#navegacion">
                    <span class="sr-only">Menú</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navegacion">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="<?= BASEURL ?>inicio/">Inicio</a>
                    </li>
                    <li>
                        <a href="<?= BASEURL ?>administracion/">Administración</a>
                    </li>
                    <li>
                        <a href="<?= BASEURL ?>cobranza">Cobranza</a>
                    </li>
                    <li>
                        <a href="<?= BASEURL ?>compras/">Compras</a>
                    </li>
                    
                </ul>
            </div>
        </div>
    </nav>
</header>