<header>
    <div class="container">
        <div id="mainLogo">
            <img src="<?= BASEURL ?>public/img/logo.png">
        </div>
    </div>
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="navegacion">
                    <span class="sr-only">Menú</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navegacion">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="">Inicio</a>
                    </li>
                    <li>
                        <a href="">Administración</a>
                    </li>
                    <li>
                        <a href="">Cobranza</a>
                    </li>
                    <li>
                        <a href="">Almacenes</a>
                    </li>
                    <li>
                        <a href="">Ventas</a>
                    </li>
                    <li>
                        <a href="">Compras</a>
                    </li>
                    <li>
                        <a href="">Balance Scorecard</a>
                    </li>
                    <li>
                        <a href="">Contabilidad</a>
                    </li>
                    <li>
                        <a href="">Producción</a>
                    </li>
                    <li>
                        <a href="">Usuarios</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>