<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title><?= APP_NAME ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <!-- Place favicon.ico in the root directory -->

        <link rel="stylesheet" href="<?= BASEURL ?>public/css/normalize.css">
        <link rel="stylesheet" href="<?= BASEURL ?>public/css/bootstrap.min.css">
        <link rel="stylesheet" href="<?= BASEURL ?>public/css/main.css">
        <script src="<?= BASEURL ?>public/js/vendor/modernizr.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <!-- header -->
        <?php require_once BASEPATH . 'core' . DIRECTORY_SEPARATOR . 'Layout.php'; ?>
        <!-- fin header -->
        <!-- contenedor principal -->
        <section class="container-fluid">
            
        </section>
        <!-- fin contenedor principal -->
        <!-- footer -->
        <?php $layout->footer() ?>
        <!-- fin footer -->
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="<?= BASEURL ?>public/js/vendor/jquery.min.js"><\/script>')</script>
        <script src="<?= BASEURL ?>public/js/bootstrap.min.js"></script>
        <script src="<?= BASEURL ?>public/js/main.js"></script>
    </body>
</html>
